### DISCUSSION TITLE
4월 2차 미팅(2025/4/23)

### DISCUSSION THREAD

**Discussion by SlideAway** [SamshinGrandmother/CheongYakJipsa#16] [General]
# 논의 필요 사항 
## ✅ 이슈의 label 관리 여부
- 관리함으로 결정
- 라벨은 아래와 같이 관리 
---
- `status: ready` – 작업할 준비가 된 상태
- `status: in progress` – 현재 작업 중
- `status: blocked` – 외부 요인 등으로 막힌 상태
- `status: review needed` – 코드 리뷰가 필요한 상태
- `status: done` – 완료됨
- `status: cancel` – 취소됨

## ✅ 이슈 템플릿 관리 
- yaml 파일로 관리 
- 추가로 Pull Request 도 템플릿으로 관리 
---
- yaml, md 사용 가능 
- yaml이 더 관리하기 편하다고 함 
- 템플릿 예시는 코멘트 참조 

항목 | Markdown .md | YAML .yml (Form-based)
-- | -- | --
UI 형태 | 자유형 입력 (본문 전체 작성) | 입력 폼 (구성된 입력란에 맞게)
UX | 자유롭게 쓰기 | 정해진 구조로 입력
초보자 사용성 | 다소 복잡 | 훨씬 편함 (폼 기반이라 가이드가 명확함)
추천 시점 | 내부 구성원이 자유롭게 작성할 때 | 외부 기여자 or 통일된 포맷이 필요할 때 ✅
사용 예 | 회의록, 설계 문서 | 버그 제보, 기능 요청, PR 리뷰 ✅

## ✅ 코드 리뷰 정책 
- ~~코드 리뷰 정책 논의 필요~~
- ~~현행은 코드 우선 반영~~
- 리뷰어를 상대방으로, Asignee 는 자기자신으로 설정 

## ✅ 코드 컨벤션 논의 
- 이전에 팀에서 사용했던 코드 컨벤션에서 조금 완화하는 컨벤션으로 방향 논의 
  - 컨벤션이 너무 타이트하면 지켜지기 힘든 이유로 
- 디렉터리 구조

### 코드 컨벤션 
- 변수, 메소드 이름은 앞글자가 소문자인 Camel Case 
- 클래스 이름은 앞글자가 대문자인 Camel Case
- 상수는 전체 대문자 및 언더바( `_` )인 Snake Case 
- 패키지는 소문자로만 
- `@Getter`, `@Setter`, `@Data` 는 필요할때만
- `@RequiredArgsConstructor` 는 사용해도 됨 
- 저장용 클래스는 ~~Request
  - 만약 세부 기능에 대한 클래스를 만들어야 한다면 inner 클래스로 선언하여 사용 
- 반환용 클래스는 ~~Response
  - 만약 세부 기능에 대한 클래스를 만들어야 한다면 inner 클래스로 선언하여 사용 
- 검색조건용 클래스는 ~~SearchCondition
  - 만약 세부 기능에 대한 클래스를 만들어야 한다면 inner 클래스로 선언하여 사용 
추가작성 필요 (by @SlideAway )
## ✅ 코드 스타일 논의 
- ~~구글 코드스타일 권장 (xml 파일은 댓글 참조)~~
- 첨부한 xml로 코드스타일 설정

## ✅ 에러관리
 - 열거형으로 관리 
 - 인터페이스 및 열거형 만들고 리뷰 예정 (by @SlideAway )

## ✅ 디자인
 - 청약집사 대표색상, 로고 등
 - 배경화면 먼저 선정 후 색상 팔레트 확정 
 - 다음 미팅(5/7)에 의견 공유 

# 미팅 일정 
- 4/23(수)

**Comment by SlideAway** [comment]
### 버그 리포트 템플릿
```yml
name: 🐞 Bug Report
description: 애플리케이션에서 발생한 버그를 제보해주세요
labels: [type: bug]
body:
  - type: markdown
    attributes:
      value: |
        버그 제보 감사합니다! 가능한 정확히 재현할 수 있도록 아래 항목을 상세하게 작성해주세요.

  - type: input
    id: title
    attributes:
      label: 버그 제목
      description: 간단하게 어떤 문제가 있었는지 요약해주세요.
      placeholder: 예) 로그인 시 500 에러 발생
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 재현 절차 (Steps to Reproduce)
      description: 버그를 재현할 수 있는 단계를 하나씩 적어주세요.
      placeholder: |
        1. 로그인 페이지로 이동
        2. 아이디와 비밀번호 입력
        3. 로그인 버튼 클릭
        4. 500 에러 발생
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 예상 동작
      description: 원래 기대했던 동작은 무엇인가요?
      placeholder: 예) 로그인 성공 후 대시보드로 이동

  - type: textarea
    id: actual
    attributes:
      label: 실제 동작
      description: 실제로 발생한 문제는 무엇인가요?
      placeholder: 예) 500 에러와 함께 흰 화면이 나타남

  - type: input
    id: env
    attributes:
      label: 환경 정보
      description: 어떤 브라우저/OS/기기에서 발생했는지 알려주세요.
      placeholder: 예) Chrome 123.0.0 / macOS 14.3.1

  - type: textarea
    id: logs
    attributes:
      label: 에러 로그 (선택)
      description: 관련된 콘솔 또는 서버 로그가 있다면 붙여주세요.
      render: shell

```

**Reply by SlideAway** [reply]
### 기능 추가 명세 템플릿 
```yml
name: ✨ Feature Request
description: 새로운 기능을 제안해주세요
labels: [type: feature]
body:
  - type: markdown
    attributes:
      value: |
        새로운 기능 제안 감사합니다! 아래 항목들을 작성해서 아이디어를 구체화해주세요.

  - type: input
    id: title
    attributes:
      label: 기능 이름 또는 제목
      placeholder: 예) 아파트 검색 필터 기능 추가
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 왜 필요한가요? (문제 정의 또는 동기)
      description: 이 기능이 왜 필요한지, 어떤 문제를 해결하려는 건지 설명해주세요.
      placeholder: |
        사용자가 많은 청약 정보를 효율적으로 필터링하지 못해서 검색에 어려움이 있음

  - type: textarea
    id: specification
    attributes:
      label: 기능 명세 (무엇을 어떻게 만들 것인가)
      description: 예상하는 동작, 입력/출력, UI 요소, 제약사항 등을 구체적으로 작성해주세요.
      placeholder: |
        - 조건: 지역, 평수, 분양가, 청약일 기준 필터
        - UI: 검색바 + 필터 드롭다운
        - 동작: 서버에서 조건 기반 조회 API 호출

  - type: textarea
    id: alternative
    attributes:
      label: 고려했던 다른 방법
      description: 다른 아이디어나 해결방법이 있었나요?

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 참고할 자료, 이미지, 링크 등

```
